### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by kinseyy** [Moonlight-Panel/Moonlight#186]
![image](https://github.com/Moonlight-Panel/Moonlight/assets/86409467/0d79a6c8-eb6a-4bae-9ff0-611d3f43f293)

**Comment by kinseyy** [comment]
Can someone help me?

**Comment by Spielepapagei** [comment]
please check your Config and database. Make sure that you follow the installation guide.

**Comment by Marcel-Baumgartner** [comment]
please send the whole log ^^

**Comment by kinseyy** [comment]
```
[INFO] [20:13:46] (DatabaseCheckupService) 41 migrations pending. Updating now
[INFO] [20:13:46] (DatabaseCheckupService) Creating backup from database
[INFO] [20:13:46] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:13:46] (ConfigService) Reloaded configuration file
[INFO] [20:13:46] (DatabaseCheckupService) Saving it to: storage/backups/1687464826949-mysql.sql
[INFO] [20:13:46] (DatabaseCheckupService) Starting backup...
Unhandled exception. System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 93
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.Perform() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 49
   at Moonlight.Program.Main(String[] args) in /src/Moonlight/Program.cs:line 51
   at Moonlight.Program.<Main>(String[] args)
[INFO] [20:14:49] (Program) Working dir: /app
[INFO] [20:14:49] (Program) Running pre-init tasks
[INFO] [20:14:49] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:14:50] (ConfigService) Reloaded configuration file
[INFO] [20:14:50] (DatabaseCheckupService) Checking database
[INFO] [20:14:53] (DatabaseCheckupService) Checking for pending migrations
[INFO] [20:14:53] (DatabaseCheckupService) 41 migrations pending. Updating now
[INFO] [20:14:53] (DatabaseCheckupService) Creating backup from database
[INFO] [20:14:53] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:14:53] (ConfigService) Reloaded configuration file
[INFO] [20:14:53] (DatabaseCheckupService) Saving it to: storage/backups/1687464893373-mysql.sql
[INFO] [20:14:53] (DatabaseCheckupService) Starting backup...
Unhandled exception. System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 93
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.Perform() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 49
   at Moonlight.Program.Main(String[] args) in /src/Moonlight/Program.cs:line 51
   at Moonlight.Program.<Main>(String[] args)
[INFO] [20:15:56] (Program) Working dir: /app
[INFO] [20:15:56] (Program) Running pre-init tasks
[INFO] [20:15:56] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:15:56] (ConfigService) Reloaded configuration file
[INFO] [20:15:56] (DatabaseCheckupService) Checking database
[INFO] [20:15:59] (DatabaseCheckupService) Checking for pending migrations
[INFO] [20:15:59] (DatabaseCheckupService) 41 migrations pending. Updating now
[INFO] [20:15:59] (DatabaseCheckupService) Creating backup from database
[INFO] [20:15:59] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:15:59] (ConfigService) Reloaded configuration file
[INFO] [20:15:59] (DatabaseCheckupService) Saving it to: storage/backups/1687464959965-mysql.sql
[INFO] [20:15:59] (DatabaseCheckupService) Starting backup...
Unhandled exception. System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 93
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.Perform() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 49
   at Moonlight.Program.Main(String[] args) in /src/Moonlight/Program.cs:line 51
   at Moonlight.Program.<Main>(String[] args)
[INFO] [20:17:03] (Program) Working dir: /app
[INFO] [20:17:03] (Program) Running pre-init tasks
[INFO] [20:17:03] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:17:03] (ConfigService) Reloaded configuration file
[INFO] [20:17:03] (DatabaseCheckupService) Checking database
[INFO] [20:17:06] (DatabaseCheckupService) Checking for pending migrations
[INFO] [20:17:06] (DatabaseCheckupService) 41 migrations pending. Updating now
[INFO] [20:17:06] (DatabaseCheckupService) Creating backup from database
[INFO] [20:17:06] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:17:06] (ConfigService) Reloaded configuration file
[INFO] [20:17:06] (DatabaseCheckupService) Saving it to: storage/backups/1687465026709-mysql.sql
[INFO] [20:17:06] (DatabaseCheckupService) Starting backup...
Unhandled exception. System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 93
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.Perform() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 49
   at Moonlight.Program.Main(String[] args) in /src/Moonlight/Program.cs:line 51
   at Moonlight.Program.<Main>(String[] args)
[INFO] [20:18:09] (Program) Working dir: /app
[INFO] [20:18:09] (Program) Running pre-init tasks
[INFO] [20:18:09] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:18:09] (ConfigService) Reloaded configuration file
[INFO] [20:18:10] (DatabaseCheckupService) Checking database
[INFO] [20:18:12] (DatabaseCheckupService) Checking for pending migrations
[INFO] [20:18:13] (DatabaseCheckupService) 41 migrations pending. Updating now
[INFO] [20:18:13] (DatabaseCheckupService) Creating backup from database
[INFO] [20:18:13] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:18:13] (ConfigService) Reloaded configuration file
[INFO] [20:18:13] (DatabaseCheckupService) Saving it to: storage/backups/1687465093244-mysql.sql
[INFO] [20:18:13] (DatabaseCheckupService) Starting backup...
Unhandled exception. System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 93
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.Perform() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 49
   at Moonlight.Program.Main(String[] args) in /src/Moonlight/Program.cs:line 51
   at Moonlight.Program.<Main>(String[] args)
[INFO] [20:19:16] (Program) Working dir: /app
[INFO] [20:19:16] (Program) Running pre-init tasks
[INFO] [20:19:16] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:19:16] (ConfigService) Reloaded configuration file
[INFO] [20:19:16] (DatabaseCheckupService) Checking database
[INFO] [20:19:19] (DatabaseCheckupService) Checking for pending migrations
[INFO] [20:19:19] (DatabaseCheckupService) 41 migrations pending. Updating now
[INFO] [20:19:19] (DatabaseCheckupService) Creating backup from database
[INFO] [20:19:19] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:19:19] (ConfigService) Reloaded configuration file
[INFO] [20:19:19] (DatabaseCheckupService) Saving it to: storage/backups/1687465159592-mysql.sql
[INFO] [20:19:19] (DatabaseCheckupService) Starting backup...
Unhandled exception. System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 93
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.Perform() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 49
   at Moonlight.Program.Main(String[] args) in /src/Moonlight/Program.cs:line 51
   at Moonlight.Program.<Main>(String[] args)
[INFO] [20:20:22] (Program) Working dir: /app
[INFO] [20:20:22] (Program) Running pre-init tasks
[INFO] [20:20:22] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:20:22] (ConfigService) Reloaded configuration file
[INFO] [20:20:23] (DatabaseCheckupService) Checking database
[INFO] [20:20:25] (DatabaseCheckupService) Checking for pending migrations
[INFO] [20:20:25] (DatabaseCheckupService) 41 migrations pending. Updating now
[INFO] [20:20:25] (DatabaseCheckupService) Creating backup from database
[INFO] [20:20:25] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:20:25] (ConfigService) Reloaded configuration file
[INFO] [20:20:25] (DatabaseCheckupService) Saving it to: storage/backups/1687465225893-mysql.sql
[INFO] [20:20:25] (DatabaseCheckupService) Starting backup...
Unhandled exception. System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 93
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.Perform() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 49
   at Moonlight.Program.Main(String[] args) in /src/Moonlight/Program.cs:line 51
   at Moonlight.Program.<Main>(String[] args)
[INFO] [20:21:28] (Program) Working dir: /app
[INFO] [20:21:28] (Program) Running pre-init tasks
[INFO] [20:21:28] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:21:29] (ConfigService) Reloaded configuration file
[INFO] [20:21:29] (DatabaseCheckupService) Checking database
[INFO] [20:21:31] (DatabaseCheckupService) Checking for pending migrations
[INFO] [20:21:32] (DatabaseCheckupService) 41 migrations pending. Updating now
[INFO] [20:21:32] (DatabaseCheckupService) Creating backup from database
[INFO] [20:21:32] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:21:32] (ConfigService) Reloaded configuration file
[INFO] [20:21:32] (DatabaseCheckupService) Saving it to: storage/backups/1687465292173-mysql.sql
[INFO] [20:21:32] (DatabaseCheckupService) Starting backup...
Unhandled exception. System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 93
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.Perform() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 49
   at Moonlight.Program.Main(String[] args) in /src/Moonlight/Program.cs:line 51
   at Moonlight.Program.<Main>(String[] args)
[INFO] [20:22:35] (Program) Working dir: /app
[INFO] [20:22:35] (Program) Running pre-init tasks
[INFO] [20:22:35] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:22:35] (ConfigService) Reloaded configuration file
[INFO] [20:22:35] (DatabaseCheckupService) Checking database
[INFO] [20:22:38] (DatabaseCheckupService) Checking for pending migrations
[INFO] [20:22:38] (DatabaseCheckupService) 41 migrations pending. Updating now
[INFO] [20:22:38] (DatabaseCheckupService) Creating backup from database
[INFO] [20:22:38] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:22:38] (ConfigService) Reloaded configuration file
[INFO] [20:22:38] (DatabaseCheckupService) Saving it to: storage/backups/1687465358515-mysql.sql
[INFO] [20:22:38] (DatabaseCheckupService) Starting backup...
Unhandled exception. System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 93
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.Perform() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 49
   at Moonlight.Program.Main(String[] args) in /src/Moonlight/Program.cs:line 51
   at Moonlight.Program.<Main>(String[] args)
[INFO] [20:23:41] (Program) Working dir: /app
[INFO] [20:23:41] (Program) Running pre-init tasks
[INFO] [20:23:41] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:23:41] (ConfigService) Reloaded configuration file
[INFO] [20:23:41] (DatabaseCheckupService) Checking database
[INFO] [20:23:44] (DatabaseCheckupService) Checking for pending migrations
[INFO] [20:23:45] (DatabaseCheckupService) 41 migrations pending. Updating now
[INFO] [20:23:45] (DatabaseCheckupService) Creating backup from database
[INFO] [20:23:45] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:23:45] (ConfigService) Reloaded configuration file
[INFO] [20:23:45] (DatabaseCheckupService) Saving it to: storage/backups/1687465425075-mysql.sql
[INFO] [20:23:45] (DatabaseCheckupService) Starting backup...
Unhandled exception. System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 93
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.Perform() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 49
   at Moonlight.Program.Main(String[] args) in /src/Moonlight/Program.cs:line 51
   at Moonlight.Program.<Main>(String[] args)
[INFO] [20:24:48] (Program) Working dir: /app
[INFO] [20:24:48] (Program) Running pre-init tasks
[INFO] [20:24:48] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:24:48] (ConfigService) Reloaded configuration file
[INFO] [20:24:48] (DatabaseCheckupService) Checking database
[INFO] [20:24:51] (DatabaseCheckupService) Checking for pending migrations
[INFO] [20:24:51] (DatabaseCheckupService) 41 migrations pending. Updating now
[INFO] [20:24:51] (DatabaseCheckupService) Creating backup from database
[INFO] [20:24:51] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:24:51] (ConfigService) Reloaded configuration file
[INFO] [20:24:51] (DatabaseCheckupService) Saving it to: storage/backups/1687465491750-mysql.sql
[INFO] [20:24:51] (DatabaseCheckupService) Starting backup...
Unhandled exception. System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 93
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.Perform() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 49
   at Moonlight.Program.Main(String[] args) in /src/Moonlight/Program.cs:line 51
   at Moonlight.Program.<Main>(String[] args)
[INFO] [20:25:54] (Program) Working dir: /app
[INFO] [20:25:54] (Program) Running pre-init tasks
[INFO] [20:25:54] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:25:54] (ConfigService) Reloaded configuration file
[INFO] [20:25:55] (DatabaseCheckupService) Checking database
[INFO] [20:25:57] (DatabaseCheckupService) Checking for pending migrations
[INFO] [20:25:58] (DatabaseCheckupService) 41 migrations pending. Updating now
[INFO] [20:25:58] (DatabaseCheckupService) Creating backup from database
[INFO] [20:25:58] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:25:58] (ConfigService) Reloaded configuration file
[INFO] [20:25:58] (DatabaseCheckupService) Saving it to: storage/backups/1687465558039-mysql.sql
[INFO] [20:25:58] (DatabaseCheckupService) Starting backup...
Unhandled exception. System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 93
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.Perform() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 49
   at Moonlight.Program.Main(String[] args) in /src/Moonlight/Program.cs:line 51
   at Moonlight.Program.<Main>(String[] args)
[INFO] [20:27:01] (Program) Working dir: /app
[INFO] [20:27:01] (Program) Running pre-init tasks
[INFO] [20:27:01] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:27:01] (ConfigService) Reloaded configuration file
[INFO] [20:27:01] (DatabaseCheckupService) Checking database
[INFO] [20:27:04] (DatabaseCheckupService) Checking for pending migrations
[INFO] [20:27:04] (DatabaseCheckupService) 41 migrations pending. Updating now
[INFO] [20:27:04] (DatabaseCheckupService) Creating backup from database
[INFO] [20:27:04] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:27:04] (ConfigService) Reloaded configuration file
[INFO] [20:27:04] (DatabaseCheckupService) Saving it to: storage/backups/1687465624703-mysql.sql
[INFO] [20:27:04] (DatabaseCheckupService) Starting backup...
Unhandled exception. System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 93
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.BackupDatabase() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 98
   at Moonlight.App.Helpers.DatabaseCheckupService.Perform() in /src/Moonlight/App/Helpers/DatabaseCheckupService.cs:line 49
   at Moonlight.Program.Main(String[] args) in /src/Moonlight/Program.cs:line 51
   at Moonlight.Program.<Main>(String[] args)
[INFO] [20:28:07] (Program) Working dir: /app
[INFO] [20:28:07] (Program) Running pre-init tasks
[INFO] [20:28:07] (ConfigService) Reading config from 'storage/configs/config.json'
[INFO] [20:28:08] (ConfigService) Reloaded configuration file
[INFO] [20:28:08] (DatabaseCheckupService) Checking database
```

**Comment by Marcel-Baumgartner** [comment]
Thanks, i will start to fix it. I notify you when i am done

**Comment by kinseyy** [comment]
okie.

**Comment by Marcel-Baumgartner** [comment]
i have not managed to replicate the error. but in the latest version (which you can get using the moonlight install script in the readme) it should not crash when the error occurs. If you need further assistance add me on discord "masusniper" or join the discord server ( https://discord.gg/TJaspT7A8p )
