### ISSUE TITLE
Issue Plugins 👍 

### ISSUE THREAD

**Issue by FlashModz** [Moonlight-Panel/Moonlight#325]
Hi the team,

I have an issue with the plugins tab on a fresh install.
Can you help me ?

![image](https://github.com/Moonlight-Panel/Moonlight/assets/7557217/e82353a1-d87b-42af-b56f-3bda61a5210e)

**Comment by FlashModz** [comment]
Octokit.RateLimitExceededException: API rate limit exceeded for 51.210.149.127. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
   at Octokit.Connection.HandleErrors(IResponse response) in /_/Octokit/Http/Connection.cs:line 729
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken, Func`2 preprocessResponseBody) in /_/Octokit/Http/Connection.cs:line 710
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken, Func`2 preprocessResponseBody) in /_/Octokit/Http/Connection.cs:line 695
   at Octokit.Internal.ReadOnlyPagedCollection`1.GetNextPage() in /_/Octokit/Http/ReadOnlyPagedCollection.cs:line 38
   at Octokit.ApiPagination.GetAllPages[T](Func`1 getFirstPage, Uri uri)
   at Moonlight.App.Services.MoonlightService.FetchChangeLog() in /src/Moonlight/App/Services/MoonlightService.cs:line 51
{"message":"API rate limit exceeded for 51.210.149.127. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

2023-10-14 01:01:24.911 +00:00 [ERR] Health check Daemons with status Unhealthy completed after 46.2527ms with message 'All node daemons are offline'
2023-10-14 01:01:24.911 +00:00 [ERR] Health check Nodes with status Unhealthy completed after 45.3967ms with message 'All nodes are offline'
2023-10-14 01:01:24.978 +00:00 [WRN] Unable to fetch health check data
2023-10-14 01:01:24.979 +00:00 [WRN] 
System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Moonlight.Shared.Views.Admin.Index.LoadHealthCheckData(LazyLoader lazyLoader) in /src/Moonlight/Shared/Views/Admin/Index.razor:line 160
2023-10-14 01:01:41.452 +00:00 [WRN] 
Octokit.RateLimitExceededException: API rate limit exceeded for 51.210.149.127. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
   at Octokit.Connection.HandleErrors(IResponse response) in /_/Octokit/Http/Connection.cs:line 729
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken, Func`2 preprocessResponseBody) in /_/Octokit/Http/Connection.cs:line 710
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken, Func`2 preprocessResponseBody) in /_/Octokit/Http/Connection.cs:line 695
   at Octokit.ApiConnection.GetPage[TU](Uri uri, IDictionary`2 parameters, String accepts, ApiOptions options, Func`2 preprocessResponseBody) in /_/Octokit/Http/ApiConnection.cs:line 672
   at Octokit.ApiConnection.<>c__DisplayClass19_0`1.<<GetAll>b__0>d.MoveNext() in /_/Octokit/Http/ApiConnection.cs:line 230
--- End of stack trace from previous location ---
   at Octokit.ApiPagination.GetAllPages[T](Func`1 getFirstPage, Uri uri)
   at Moonlight.App.Services.Plugins.PluginStoreService.GetPlugins() in /src/Moonlight/App/Services/Plugins/PluginStoreService.cs:line 21
   at Moonlight.Shared.Views.Admin.Sys.Plugins.LoadOfficialPlugins(LazyLoader lazyLoader) in /src/Moonlight/Shared/Views/Admin/Sys/Plugins.razor:line 116
   at Moonlight.Shared.Components.Partials.LazyLoader.OnAfterRenderAsync(Boolean firstRender) in /src/Moonlight/Shared/Components/Partials/LazyLoadelimiting"}r.razor:line 30
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
{"message":"API rate limit exceeded for 51.210.149.127. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-

**Comment by FlashModz** [comment]
Same issue for void command on discord bot tab.
Maybe its because i have not setup an bot, but why does not return an warning message ?

With this error :
2023-10-14 01:04:32.837 +00:00 [WRN] 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Moonlight.Shared.Views.Admin.Sys.DiscordBot.VoidCommands() in /src/Moonlight/Shared/Views/Admin/Sys/DiscordBot.razor:line 37
   at Moonlight.Shared.Components.Forms.WButton.<Do>b__25_0() in /src/Moonlight/Shared/Components/Forms/WButton.razor:line 42
   at Moonlight.Shared.Components.Forms.WButton.Do() in /src/Moonlight/Shared/Components/Forms/WButton.razor:line 39
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by Marcel-Baumgartner** [comment]
The discord bot is not finished and as of that will not work

**Comment by Marcel-Baumgartner** [comment]
The plugins tab crashinf indivates that youe iü has been ratelimited by github

**Comment by FlashModz** [comment]
Ratelimit and Beta features.
This issue is solved on discord :)
