### ISSUE TITLE
Incubator error

### ISSUE THREAD

**Issue by haxoder** [Moonlight-Panel/Moonlight#400]
### Current Behavior

I've started first test server and this is the prompt I get

### Expected Behavior

Should start a normal server

### Steps to Reproduce

Start a server

### Panel Version

bf6641c (up-to-date)

### Daemon Version

probably latest (installed today)

### Wings Version

probably latest (installed today)

### Games and/or Images Affected

Minecraft (Purpur)

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Error Logs

```bash
container@pterodactyl~ java --add-modules=jdk.incubator.vector -Xms128M -Xmx1024M -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
WARNING: Using incubator modules: jdk.incubator.vector
Downloading mojang_1.20.4.jar
Failed to download mojang_1.20.4.jar
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1719)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1518)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:589)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
Caused by: java.io.EOFException: S
        ... 17 more
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at io.papermc.paperclip.Main.main(Main.java:26)
SL peer shut down incorrectly
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:28)
        at io.papermc.paperclip.Paperclip.setupClasspath(Paperclip.java:63)
        at io.papermc.paperclip.DownloadContext.download(DownloadContext.java:55)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at java.base/java.net.URL.openStream(URL.java:1161)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [ ] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Dannyx1604** [comment]
`Remote host terminated the handshake`

Looks like an issue on your side

**Comment by Masu-Baumgartner** [comment]
Not a moonlight issue

**Comment by haxoder** [comment]
Any help tho?

**Comment by Masu-Baumgartner** [comment]
Nooo? We do not support imported eggs. You haved been warned by moonlight while importing

**Comment by haxoder** [comment]
I legit used an egg that was recommended by installation docs... https://help.moonlightpanel.xyz/gettingStarted

**Comment by haxoder** [comment]
Which egg can I use than, if I want to run minecraft

**Comment by Dannyx1604** [comment]
> I legit used an egg that was recommended by installation docs... https://help.moonlightpanel.xyz/gettingStarted

It's an issue with your machine, so read error messages and try to understand and fix the issue

**Comment by mxritzdev** [comment]
https://discord.com/channels/1075368155830034433/1227605943584292934 maybe use this image for v2, it works
