### ISSUE TITLE
Panel cannot connect to the database

### ISSUE THREAD

**Issue by sez76** [Moonlight-Panel/Moonlight#403]
### Current Behavior

Panel cannot connect to the internal docker database

### Expected Behavior

After the installation, the docker container panel change status to restarting after one web request, and display the log error

### Steps to Reproduce

Script started on 2024-04-30 13:07:51+00:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="209" LINES="51"]
root@moonlight-panel:~# bash <(curl https://get-moonlight.app)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0   1155      0 --:--:-- --:--:-- --:--:--  1157
Installing moonlight cli
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2579  100  2579    0     0  24111      0 --:--:-- --:--:-- --:--:-- 24102
Running installer
Welcome to the Moonlight installer made by @masuowo

[ 💬 ] Running version: v2.0.0
[ ✔️ ] Running as root
[ ✔️ ] Aptitude found
[ 💬 ] Detected architecture: arm64

Select the software you want to install/update/uninstall:

[ 💬 ] Selected software 'Moonlight Panel' with 1 dependencies
[ 💬 ] Status: Not installed

Select the action you want to perform
[ ✔️ ] 'Docker' is already installed
[ 💬 ] Installing 'Moonlight Panel'

Select the build channel you want to use:
[ ✔️ ] NodeJS already installed
[ ✔️ ] Sass already installed
[ ✔️ ] git already installed
[ 💬 ] Created tmp build directories
Cloning into '/tmp/mlbuild'...
[ ✔️ ] Successfully cloned repository
build.bat: line 1: @echo: command not found
[ ✔️ ] Successfully compiled scss
[+] Building 0.5s (20/20) FINISHED                                                                                                                                                                docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                        0.0s
 => => transferring dockerfile: 766B                                                                                                                                                                        0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:7.0                                                                                                                                        0.2s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:7.0                                                                                                                                           0.2s
 => [internal] load .dockerignore                                                                                                                                                                           0.0s
 => => transferring context: 356B                                                                                                                                                                           0.0s
 => [build 1/7] FROM mcr.microsoft.com/dotnet/sdk:7.0@sha256:d6e33bffd4e9348c932ea18b7764caea791c656fa47a2fcbeafac0a488d7c119                                                                               0.0s
 => [internal] load build context                                                                                                                                                                           0.2s
 => => transferring context: 13.05MB                                                                                                                                                                        0.2s
 => [base 1/2] FROM mcr.microsoft.com/dotnet/aspnet:7.0@sha256:b51bc3980a818f4b8f6bf308470bf686b398fb6198d0be5ceb6957f65342b0f1                                                                             0.0s
 => CACHED [base 2/2] WORKDIR /app                                                                                                                                                                          0.0s
 => CACHED [final 1/4] WORKDIR /app                                                                                                                                                                         0.0s
 => CACHED [build 2/7] WORKDIR /src                                                                                                                                                                         0.0s
 => CACHED [build 3/7] COPY [Moonlight/Moonlight.csproj, Moonlight/]                                                                                                                                        0.0s
 => CACHED [build 4/7] RUN dotnet restore "Moonlight/Moonlight.csproj"                                                                                                                                      0.0s
 => CACHED [build 5/7] COPY . .                                                                                                                                                                             0.0s
 => CACHED [build 6/7] WORKDIR /src/Moonlight                                                                                                                                                               0.0s
 => CACHED [build 7/7] RUN dotnet build "Moonlight.csproj" -c Release -o /app/build                                                                                                                         0.0s
 => CACHED [publish 1/1] RUN dotnet publish "Moonlight.csproj" -c Release -o /app/publish /p:UseAppHost=false                                                                                               0.0s
 => CACHED [final 2/4] COPY --from=publish /app/publish .                                                                                                                                                   0.0s
 => CACHED [final 3/4] RUN mkdir -p /app/Assets                                                                                                                                                             0.0s
 => CACHED [final 4/4] COPY ./Moonlight/Assets ./Assets                                                                                                                                                     0.0s
 => exporting to image                                                                                                                                                                                      0.0s
 => => exporting layers                                                                                                                                                                                     0.0s
 => => writing image sha256:b22b6e8d98cb975fb8ef464fa585cbd2457dbd0ecd3dd9c2d506a87eb294f3fb                                                                                                                0.0s
 => => naming to docker.io/moonlightpanel/moonlight:custom                                                                                                                                                  0.0s
[ ✔️ ] Successfully built docker image
Do you want to use ssl (for https connections) [y/n] (n): n
Please enter a ip address or domain you want to use: (89.168.40.66): 89.168.40.66
Please enter the http port moonlight should listen on (80): 80
[ ✔️ ] Port 80 is unused
[ 💬 ] App URL: http://89.168.40.66:80
Do you want to use the internal database? [y/n] (y): y
[ 💬 ] UFW disabled. Skipping firewall configurations
[ ✔️ ] Volume 'moonlight' created
[ ✔️ ] Volume 'moonlight_db' created
[ ✔️ ] Successfully created volumes
43024546c41579d3c8f3f643efde92bf985258a730606201cc5242a4ecb89829
[ ✔️ ] Successfully deployed internal database
[ ✔️ ] Core configuration file has been written
3f8f79b8f3f1c284262b69a61ec869c3d5ed748728a5eed82a4cedf49b40f04d
[ ✔️ ] Successfully deployed moonlight container
[ 💬 ] Writing update flags to disk
[ 💬 ] Done! Moonlight is successfully installed and can be reached under the following urls. Please keep in mind moonlight might take some time to boot up and create the initial data on the first startup

[ 💬 ] App URL: http://89.168.40.66:80

[ 💬 ] Some useful commands:
[ 💬 ] mlcli moonlight login    See the default login for moonlight
[ 💬 ] mlcli moonlight logs     Shows the logs of moonlight

[ 💬 ] See https://help.moonlightpanel.xyz/gettingStarted for a guide how to get started and do the initial configuration
root@moonlight-panel:~# mlcli moonlight login
Searching for default login in moonlight logs
Unhandled exception. MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 1146
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 438
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 403
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 408
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 98
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 128
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 929
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 423
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 382
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
   at Moonlight.Core.Database.DataContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in /src/Moonlight/Core/Database/DataContext.cs:line 45
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_ProviderName()
   at MoonCore.Helpers.DatabaseCheckHelper.Check(DbContext dbContext, Boolean enableConnectCheck)
   at Program.<Main>$(String[] args) in /src/Moonlight/Program.cs:line 81
   at Program.<Main>(String[] args)
Unhandled exception. MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 1146
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 438
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 403
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 408
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 98
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 128
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 929
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 423
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 382
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
   at Moonlight.Core.Database.DataContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in /src/Moonlight/Core/Database/DataContext.cs:line 45
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_ProviderName()
   at MoonCore.Helpers.DatabaseCheckHelper.Check(DbContext dbContext, Boolean enableConnectCheck)
   at Program.<Main>$(String[] args) in /src/Moonlight/Program.cs:line 81
   at Program.<Main>(String[] args)
Unhandled exception. MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 1146
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 438
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 403
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 408
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 98
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 128
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 929
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 423
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 382
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
   at Moonlight.Core.Database.DataContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in /src/Moonlight/Core/Database/DataContext.cs:line 45
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_ProviderName()
   at MoonCore.Helpers.DatabaseCheckHelper.Check(DbContext dbContext, Boolean enableConnectCheck)
   at Program.<Main>$(String[] args) in /src/Moonlight/Program.cs:line 81
   at Program.<Main>(String[] args)
root@moonlight-panel:~# exit
exit

Script done on 2024-04-30 13:08:40+00:00 [COMMAND_EXIT_CODE="1"]

### Panel Version

1.4.0

### Daemon Version

1.4.2

### Wings Version

1.4.2

### Error Logs

```bash
12:53:27 [INF] AsyncMethodBuilderCore Loading features
12:53:27 [INF] AsyncMethodBuilderCore Loaded feature 'Servers' by 'MasuOwO and contributors'
12:53:27 [INF] AsyncMethodBuilderCore Loaded feature 'File Manager Components' by 'MasuOwO'
12:53:27 [INF] AsyncMethodBuilderCore Loaded feature 'Moonlight Core' by 'MasuOwO and contributors'
Unhandled exception. MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 1146
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int32 startTickCount, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 438
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 403
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, String logMessage, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 408
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 98
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 128
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 929
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 423
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 382
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
   at Moonlight.Core.Database.DataContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in /src/Moonlight/Core/Database/DataContext.cs:line 45
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_ProviderName()
   at MoonCore.Helpers.DatabaseCheckHelper.Check(DbContext dbContext, Boolean enableConnectCheck)
   at Program.<Main>$(String[] args) in /src/Moonlight/Program.cs:line 81
   at Program.<Main>(String[] args)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Masu-Baumgartner** [comment]
What database are you using? The integrated or the external one?

**Comment by sez76** [comment]
The integrated

**Comment by Masu-Baumgartner** [comment]
What distribution are you using?

**Comment by sez76** [comment]
and I use Oracle cloud provider, the instance shape is a VM.Standard.A1.Flex 2 core 6 gb RAM
root@moonlight-panel:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by Masu-Baumgartner** [comment]
Orcale has weird firewall setting via ip tables so the port 3307 database cannot be used. Its not a moonlight issue

**Comment by sez76** [comment]
ah alright, thanks for your help, I go look on my oracle fw
