### ISSUE TITLE
Unable to load shared library 'Mono.Unix' or one of its dependencies.

### ISSUE THREAD

**Issue by gOOvER** [Moonlight-Panel/Moonlight#412]
### Current Behavior

After update to latest Panel and Daemon i get `Unable to load shared library 'Mono.Unix' or one of its dependencies.`

### Expected Behavior

Daemon should start

### Steps to Reproduce

- update Daemon
- start Daemon

### Panel Version

V2 EA

### Daemon Version

V2 EA

### Error Logs

```bash
14:37:02 [INF] ExecutionContext Application is shutting down...
14:37:09 [INF] AsyncTaskMethodBuilder Starting MoonlightDaemon v2
14:37:09 [INF] GenericWebHostService Now listening on: https://0.0.0.0:8080
14:37:09 [INF] ConsoleLifetime Application started. Press Ctrl+C to shut down.
14:37:09 [INF] ConsoleLifetime Hosting environment: Production
14:37:09 [INF] ExecutionContext Content root path: /var/lib/moonlight
14:37:12 [INF] AsyncTaskMethodBuilder Preparing for boot
14:37:13 [INF] AsyncTaskMethodBuilder Fetching servers from moonlight
14:37:13 [INF] ExecutionContext About to receive 2 servers
14:37:13 [WRN] ExecutionContext An unknown error occured while booting
14:37:13 [WRN] ExecutionContext 
System.DllNotFoundException: Unable to load shared library 'Mono.Unix' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/usr/local/bin/Mono.Unix.so: cannot open shared object file: No such file or directory
/usr/local/bin/libMono.Unix.so: cannot open shared object file: No such file or directory
/usr/local/bin/Mono.Unix: cannot open shared object file: No such file or directory
/usr/local/bin/libMono.Unix: cannot open shared object file: No such file or directory

   at Mono.Unix.Native.Syscall.open(String pathname, OpenFlags flags)
   at MoonCore.Helpers.Unix.UnixFileSystem..ctor(String baseDirectory)
   at MoonlightDaemon.App.Helpers.ServerFileSystem..ctor(ServerConfiguration configuration)
   at MoonlightDaemon.App.Services.ServerService.AddFromConfiguration(ServerConfiguration configuration)
   at MoonlightDaemon.App.Services.BootService.FetchServers()
   at MoonlightDaemon.App.Services.BootService.Boot()
```
```


### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Masu-Baumgartner** [comment]
Update your installer by using

`mlcli install update`

And then update your daemon again

**Comment by gOOvER** [comment]
omg, i missed that step :/

ty
