### ISSUE TITLE
Server archiving not working properly on large files

### ISSUE THREAD

**Issue by Masu-Baumgartner** [Moonlight-Panel/Moonlight#413]
### Current Behavior

Server archiving not working properly on large files, crashing after a certain amount of time

### Expected Behavior

Should work fine

### Steps to Reproduce

Archive a lot of files at the same time

### Panel Version

v2 EA

### Daemon Version

v2 EA

### Error Logs

```bash
20:32:41 [WRN] ExecutionContext
ICSharpCode.SharpZipLib.Tar.TarException: Entry closed at '1231028224' before the '1231077376' bytes specified in the header were written
at ICSharpCode.SharpZipLib.Tar.TarOutputStream.CloseEntryAsync(CancellationToken cancellationToken, Boolean isAsync)
at ICSharpCode.SharpZipLib.Tar.TarOutputStream.FinishAsync(CancellationToken cancellationToken, Boolean isAsync)
at ICSharpCode.SharpZipLib.Tar.TarOutputStream.Finish()
at ICSharpCode.SharpZipLib.Tar.TarOutputStream.Dispose(Boolean disposing)
at System.IO.Stream.Close()
at System.IO.Stream.DisposeAsync()
--- End of stack trace from previous location ---
at MoonlightDaemon.App.Helpers.ArchiveHelper.ArchiveToTar(FileStream fs, ServerFileSystem fileSystem, String[] items)
at MoonlightDaemon.App.Helpers.ArchiveHelper.ArchiveToTar(FileStream fs, ServerFileSystem fileSystem, String[] items)
at MoonlightDaemon.App.Helpers.ArchiveHelper.ArchiveToTarFile(String fullPath, ServerFileSystem fileSystem, String[] items)
at MoonlightDaemon.App.Helpers.ArchiveHelper.ArchiveToTarFile(String fullPath, ServerFileSystem fileSystem, String[] items)
at MoonlightDaemon.App.Provider.FileBackupProvider.Create(Server server, Int32 backupId)
at MoonlightDaemon.App.Services.BackupService.Create(Server server, Int32 backupId)
at MoonlightDaemon.App.Http.Controllers.ServersController.<>c__DisplayClass14_0.<<CreateBackup>b__0>d.MoveNext()
20:54:34 [WRN] ExecutionContext An error occured while creating backup for server 15
20:54:34 [WRN] ExecutionContext
ICSharpCode.SharpZipLib.Tar.TarException: Entry closed at '1232207872' before the '1232273408' bytes specified in the header were written
at ICSharpCode.SharpZipLib.Tar.TarOutputStream.CloseEntryAsync(CancellationToken cancellationToken, Boolean isAsync)
at ICSharpCode.SharpZipLib.Tar.TarOutputStream.FinishAsync(CancellationToken cancellationToken, Boolean isAsync)
at ICSharpCode.SharpZipLib.Tar.TarOutputStream.Finish()
at ICSharpCode.SharpZipLib.Tar.TarOutputStream.Dispose(Boolean disposing)
at System.IO.Stream.Close()
at System.IO.Stream.DisposeAsync()
--- End of stack trace from previous location ---
at MoonlightDaemon.App.Helpers.ArchiveHelper.ArchiveToTar(FileStream fs, ServerFileSystem fileSystem, String[] items)
at MoonlightDaemon.App.Helpers.ArchiveHelper.ArchiveToTar(FileStream fs, ServerFileSystem fileSystem, String[] items)
at MoonlightDaemon.App.Helpers.ArchiveHelper.ArchiveToTarFile(String fullPath, ServerFileSystem fileSystem, String[] items)
at MoonlightDaemon.App.Helpers.ArchiveHelper.ArchiveToTarFile(String fullPath, ServerFileSystem fileSystem, String[] items)
at MoonlightDaemon.App.Provider.FileBackupProvider.Create(Server server, Int32 backupId)
at MoonlightDaemon.App.Services.BackupService.Create(Server server, Int32 backupId)
at MoonlightDaemon.App.Http.Controllers.ServersController.<>c__DisplayClass14_0.<<CreateBackup>b__0>d.MoveNext()
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Masu-Baumgartner** [comment]
The issue happens when a file is modified while archiving. Can probably be fixed by using the stream length as size instead of the readdir output

**Comment by Masu-Baumgartner** [comment]
Fixed in https://github.com/Moonlight-Panel/MoonlightDaemon/pull/11
