### ISSUE TITLE
Updates in Admin Dashboard

### ISSUE THREAD

**Issue by LowlandwasTaken** [Moonlight-Panel/Moonlight#435]
### Current Behavior

Currently when going to the Admin Panel the Users and Servers Field just says "0". Not taking in account the users and servers that actually exist
![image](https://github.com/Moonlight-Panel/Moonlight/assets/100024843/5f8abd56-17f2-470f-abd3-1032b81dc315)

### Expected Behavior

Showing the right number of Users and Servers

### Steps to Reproduce

1. login to panel
2. Click Second Dashboard Button 
![image](https://github.com/Moonlight-Panel/Moonlight/assets/100024843/52a7b130-e524-4f55-8b75-a18593dcf7e9)
3. Tada Bug

### Panel Version

v2 EA

### Daemon Version

v2 EA

### Error Logs

```bash
root@Ubuntu-2204-jammy-amd64-base ~ # docker logs moonlight
18:11:08 INFO Program: Initializing moonlight
18:11:08 INFO Program: Successfully loaded certificate CN=panel.nightcityrp.nl
18:11:08 INFO Moonlight.Core.Services.FeatureService: Loading features
18:11:08 INFO Moonlight.Core.Services.FeatureService: Loaded feature 'Servers' 
by 'MasuOwO and contributors'
18:11:08 INFO Moonlight.Core.Services.FeatureService: Loaded feature 'File 
Manager Components' by 'MasuOwO'
18:11:08 INFO Moonlight.Core.Services.FeatureService: Loaded feature 'Moonlight 
Core' by 'MasuOwO and contributors'
18:11:08 INFO Moonlight.Core.Services.FeatureService: Pre-initializing features
18:11:08 INFO Moonlight.Core.Services.FeatureService: Initializing features
18:11:08 WARN 
Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository: 
Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be 
persisted outside of the container. Protected data will be unavailable when 
container is destroyed. For more information go to 
https://aka.ms/aspnet/dataprotectionwarning
18:11:08 INFO Moonlight.Core.Services.FeatureService: Initializing feature uis
18:11:08 INFO Moonlight.Core.Services.StartupJobService: Running startup jobs
18:11:08 WARN Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: 
No XML encryptor configured. Key {41f5a014-70d8-49ee-8ed7-f8168626cc64} may be 
persisted to storage in unencrypted form.
18:11:08 WARN Microsoft.AspNetCore.Hosting.Diagnostics: Overriding HTTP_PORTS 
'8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 
'http://0.0.0.0:80;https://0.0.0.0:443'.
18:11:08 INFO Microsoft.Hosting.Lifetime: Now listening on: http://0.0.0.0:80
18:11:08 INFO Microsoft.Hosting.Lifetime: Now listening on: https://0.0.0.0:443
18:11:08 INFO Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to 
shut down.
18:11:08 INFO Microsoft.Hosting.Lifetime: Hosting environment: Production
18:11:08 INFO Microsoft.Hosting.Lifetime: Content root path: /app
18:11:11 WARN Moonlight.Core.Services.StartupJobService: The startup job 
'Default user creation' failed: MySqlConnector.MySqlException (0x80004005): 
Couldn't connect to server
 ---> MySqlConnector.MySqlEndOfStreamException: An incomplete response was 
received from the server
   at 
MySqlConnector.Protocol.Serialization.ProtocolUtility.ReadPayloadAsync(BufferedB
yteReader bufferedByteReader, IByteHandler byteHandler, Func`1 
getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, 
ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in 
/_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 424
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior,
CancellationToken cancellationToken) in 
/_/src/MySqlConnector/Core/ServerSession.cs:line 882
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, 
MySqlConnection connection, Int64 startingTimestamp, ILoadBalancer loadBalancer,
Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) 
in /_/src/MySqlConnector/Core/ServerSession.cs:line 445
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, 
MySqlConnection connection, Int64 startingTimestamp, ILoadBalancer loadBalancer,
Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) 
in /_/src/MySqlConnector/Core/ServerSession.cs:line 564
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, 
Int64 startingTimestamp, Activity activity, Nullable`1 ioBehavior, 
CancellationToken cancellationToken) in 
/_/src/MySqlConnector/MySqlConnection.cs:line 932
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, 
Int64 startingTimestamp, Activity activity, Nullable`1 ioBehavior, 
CancellationToken cancellationToken) in 
/_/src/MySqlConnector/MySqlConnection.cs:line 938
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, 
CancellationToken cancellationToken) in 
/_/src/MySqlConnector/MySqlConnection.cs:line 419
   at MySqlConnector.MySqlConnection.Open() in 
/_/src/MySqlConnector/MySqlConnection.cs:line 381
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String 
connectionString)
   at Moonlight.Core.Database.DataContext.OnConfiguring(DbContextOptionsBuilder 
optionsBuilder) in /src/Moonlight/Core/Database/DataContext.cs:line 46
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at Moonlight.Core.Repositories.GenericRepository`1..ctor(DataContext 
dbContext) in /src/Moonlight/Core/Repositories/GenericRepository.cs:line 12
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, 
Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object 
obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, 
BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo 
culture)
   at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCa
llSiteMain(ServiceCallSite callSite, TArgument argument)
   at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.V
isitCache(ServiceCallSite callSite, RuntimeResolverContext context, 
ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.V
isitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCa
llSite(ServiceCallSite callSite, TArgument argument)
   at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.R
esolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEng
ine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at 
Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdent
ifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScop
e.GetService(Type serviceType)
   at 
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetReq
uiredService(IServiceProvider provider, Type serviceType)
   at 
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetReq
uiredService[T](IServiceProvider provider)
   at 
Moonlight.Core.CoreFeature.<>c__DisplayClass2_0.<<OnInitialized>b__0>d.MoveNext(
) in /src/Moonlight/Core/CoreFeature.cs:line 230
--- End of stack trace from previous location ---
   at 
Moonlight.Core.Services.StartupJobService.<>c__DisplayClass5_0.<<Run>b__0>d.Move
Next() in /src/Moonlight/Core/Services/StartupJobService.cs:line 43
18:11:11 WARN Moonlight.Core.Services.StartupJobService: The startup job 'Boot 
all server nodes' failed: MySqlConnector.MySqlException (0x80004005): Couldn't 
connect to server
 ---> MySqlConnector.MySqlEndOfStreamException: An incomplete response was 
received from the server
   at 
MySqlConnector.Protocol.Serialization.ProtocolUtility.ReadPayloadAsync(BufferedB
yteReader bufferedByteReader, IByteHandler byteHandler, Func`1 
getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, 
ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in 
/_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 424
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior,
CancellationToken cancellationToken) in 
/_/src/MySqlConnector/Core/ServerSession.cs:line 882
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, 
MySqlConnection connection, Int64 startingTimestamp, ILoadBalancer loadBalancer,
Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) 
in /_/src/MySqlConnector/Core/ServerSession.cs:line 445
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, 
MySqlConnection connection, Int64 startingTimestamp, ILoadBalancer loadBalancer,
Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) 
in /_/src/MySqlConnector/Core/ServerSession.cs:line 564
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, 
Int64 startingTimestamp, Activity activity, Nullable`1 ioBehavior, 
CancellationToken cancellationToken) in 
/_/src/MySqlConnector/MySqlConnection.cs:line 932
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, 
Int64 startingTimestamp, Activity activity, Nullable`1 ioBehavior, 
CancellationToken cancellationToken) in 
/_/src/MySqlConnector/MySqlConnection.cs:line 938
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, 
CancellationToken cancellationToken) in 
/_/src/MySqlConnector/MySqlConnection.cs:line 419
   at MySqlConnector.MySqlConnection.Open() in 
/_/src/MySqlConnector/MySqlConnection.cs:line 381
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String 
connectionString)
   at Moonlight.Core.Database.DataContext.OnConfiguring(DbContextOptionsBuilder 
optionsBuilder) in /src/Moonlight/Core/Database/DataContext.cs:line 46
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at Moonlight.Core.Repositories.GenericRepository`1..ctor(DataContext 
dbContext) in /src/Moonlight/Core/Repositories/GenericRepository.cs:line 12
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, 
Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object 
obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, 
BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo 
culture)
   at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCa
llSiteMain(ServiceCallSite callSite, TArgument argument)
   at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.V
isitCache(ServiceCallSite callSite, RuntimeResolverContext context, 
ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.V
isitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCa
llSite(ServiceCallSite callSite, TArgument argument)
   at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.R
esolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEng
ine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at 
Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdent
ifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at 
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScop
e.GetService(Type serviceType)
   at 
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetReq
uiredService(IServiceProvider provider, Type serviceType)
   at 
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetReq
uiredService[T](IServiceProvider provider)
   at Moonlight.Features.Servers.Services.NodeService.BootAll() in 
/src/Moonlight/Features/Servers/Services/NodeService.cs:line 31
   at 
Moonlight.Features.Servers.ServersFeature.<>c.<<OnInitialized>b__2_0>d.MoveNext(
) in /src/Moonlight/Features/Servers/ServersFeature.cs:line 70
--- End of stack trace from previous location ---
   at 
Moonlight.Core.Services.StartupJobService.<>c__DisplayClass5_0.<<Run>b__0>d.Move
Next() in /src/Moonlight/Core/Services/StartupJobService.cs:line 43
18:13:39 INFO Microsoft.Hosting.Lifetime: Application is shutting down...
18:13:41 INFO Program: Initializing moonlight
18:13:41 INFO Program: Successfully loaded certificate CN=panel.nightcityrp.nl
18:13:41 INFO Moonlight.Core.Services.FeatureService: Loading features
18:13:41 INFO Moonlight.Core.Services.FeatureService: Loaded feature 'Servers' 
by 'MasuOwO and contributors'
18:13:41 INFO Moonlight.Core.Services.FeatureService: Loaded feature 'File 
Manager Components' by 'MasuOwO'
18:13:41 INFO Moonlight.Core.Services.FeatureService: Loaded feature 'Moonlight 
Core' by 'MasuOwO and contributors'
18:13:42 INFO Moonlight.Core.Database.DataContext: Checking 'DataContext' 
(Provider: Pomelo.EntityFrameworkCore.MySql)
18:13:42 INFO Moonlight.Core.Database.DataContext: Loading pending migrations
18:13:42 INFO Moonlight.Core.Database.DataContext: Database is up-to-date
18:13:42 INFO Moonlight.Core.Services.FeatureService: Pre-initializing features
18:13:42 INFO Moonlight.Core.Services.FeatureService: Initializing features
18:13:42 WARN 
Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository: 
Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be 
persisted outside of the container. Protected data will be unavailable when 
container is destroyed. For more information go to 
https://aka.ms/aspnet/dataprotectionwarning
18:13:42 INFO Moonlight.Core.Services.FeatureService: Initializing feature uis
18:13:42 INFO Moonlight.Core.Services.StartupJobService: Running startup jobs
18:13:42 WARN Microsoft.AspNetCore.Hosting.Diagnostics: Overriding HTTP_PORTS 
'8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 
'http://0.0.0.0:80;https://0.0.0.0:443'.
18:13:42 INFO Microsoft.Hosting.Lifetime: Now listening on: http://0.0.0.0:80
18:13:42 INFO Microsoft.Hosting.Lifetime: Now listening on: https://0.0.0.0:443
18:13:42 INFO Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to 
shut down.
18:13:42 INFO Microsoft.Hosting.Lifetime: Hosting environment: Production
18:13:42 INFO Microsoft.Hosting.Lifetime: Content root path: /app
19:41:54 WARN Moonlight.Features.Servers.UI.Views.Admin.Images.Index: An error 
occured while importing a pterodactyl egg: System.ArgumentNullException: Value 
cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, 
String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at 
Moonlight.Features.Servers.Helpers.ImageConversionHelper.ImportFromEggJson(Strin
g json) in /src/Moonlight/Features/Servers/Helpers/ImageConversionHelper.cs:line
285
   at 
Moonlight.Features.Servers.UI.Views.Admin.Images.Index.<>c__DisplayClass10_0.<<I
mportEgg>b__0>d.MoveNext() in 
/src/Moonlight/Features/Servers/UI/Views/Admin/Images/Index.razor:line 309
19:42:07 WARN Moonlight.Features.Servers.UI.Views.Admin.Images.Index: An error 
occured while importing a pterodactyl egg: System.ArgumentNullException: Value 
cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, 
String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at 
Moonlight.Features.Servers.Helpers.ImageConversionHelper.ImportFromEggJson(Strin
g json) in /src/Moonlight/Features/Servers/Helpers/ImageConversionHelper.cs:line
285
   at 
Moonlight.Features.Servers.UI.Views.Admin.Images.Index.<>c__DisplayClass10_0.<<I
mportEgg>b__0>d.MoveNext() in 
/src/Moonlight/Features/Servers/UI/Views/Admin/Images/Index.razor:line 309
19:42:21 WARN Moonlight.Features.Servers.UI.Views.Admin.Images.Index: An error 
occured while importing a pterodactyl egg: System.ArgumentNullException: Value 
cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, 
String parameterName)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at 
Moonlight.Features.Servers.Helpers.ImageConversionHelper.ImportFromEggJson(Strin
g json) in /src/Moonlight/Features/Servers/Helpers/ImageConversionHelper.cs:line
285
   at 
Moonlight.Features.Servers.UI.Views.Admin.Images.Index.<>c__DisplayClass10_0.<<I
mportEgg>b__0>d.MoveNext() in 
/src/Moonlight/Features/Servers/UI/Views/Admin/Images/Index.razor:line 309
19:42:25 WARN Moonlight.Features.Servers.UI.Views.Admin.Images.Index: An error 
occured while importing a image: System.NullReferenceException: Object reference
not set to an instance of an object.
   at Moonlight.Features.Servers.UI.Views.Admin.Images.Index.Import(IBrowserFile
file) in /src/Moonlight/Features/Servers/UI/Views/Admin/Images/Index.razor:line 
279
20:00:31 ERRO Microsoft.AspNetCore.Server.Kestrel: Connection id 
"0HN511G555A3I", Request id "0HN511G555A3I:00000001": An unhandled exception was
thrown by the application.
21:55:07 WARN Moonlight.Core.UI.Components.Partials.SoftErrorHandler: A crash 
occured in the view of 'lowland': System.ArgumentNullException: Value cannot be 
null. (Parameter 'provider')
   at System.ThrowHelper.Throw(String paramName)
   at 
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetReq
uiredService[T](IServiceProvider provider)
   at 
Moonlight.Core.Extensions.IdentityServiceExtensions.SetFlag(IdentityService 
identityService, String flag, Boolean toggle) in 
/src/Moonlight/Core/Extensions/IdentityServiceExtensions.cs:line 48
   at Moonlight.Core.UI.Views.Account.Security.SetCookieConsent(Boolean flag) in
/src/Moonlight/Core/UI/Views/Account/Security.razor:line 81
   at 
Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompleti
on(Task task)
   at 
Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task 
taskToHandle, ComponentState owningComponentState)
root@Ubuntu-2204-jammy-amd64-base ~ # sudo wings diagnostics
sudo: wings: command not found
root@Ubuntu-2204-jammy-amd64-base ~ # mlcli daemon logs
00:09:43 [INF] AsyncTaskMethodBuilder Starting MoonlightDaemon v2
00:09:43 [INF] GenericWebHostService Now listening on: https://0.0.0.0:8080
00:09:43 [INF] ConsoleLifetime Application started. Press Ctrl+C to shut down.
00:09:43 [INF] ConsoleLifetime Hosting environment: Production
00:09:43 [INF] ExecutionContext Content root path: /var/lib/moonlight
00:09:46 [INF] AsyncTaskMethodBuilder Preparing for boot
00:09:46 [INF] AsyncTaskMethodBuilder Fetching servers from moonlight
00:09:47 [INF] ExecutionContext About to receive 0 servers
00:09:47 [INF] ExecutionContext Fetched servers. Closing websocket connection
00:09:47 [INF] AsyncTaskMethodBuilder Finishing boot
00:09:47 [INF] AsyncTaskMethodBuilder Restoring docker containers
00:09:47 [INF] AsyncTaskMethodBuilder Starting ftp server
00:09:47 [INF] AsyncTaskMethodBuilder Ftp server listening on 0.0.0.0:2021
00:14:43 [INF] ExecutionContext Application is shutting down...
00:14:43 [INF] AsyncVoidMethodBuilder Stopping ftp server
00:18:21 [INF] AsyncTaskMethodBuilder Starting MoonlightDaemon v2
00:18:22 [INF] GenericWebHostService Now listening on: http://0.0.0.0:8080
00:18:22 [INF] ConsoleLifetime Application started. Press Ctrl+C to shut down.
00:18:22 [INF] ConsoleLifetime Hosting environment: Production
00:18:22 [INF] ExecutionContext Content root path: /var/lib/moonlight
00:18:25 [INF] AsyncTaskMethodBuilder Preparing for boot
00:18:25 [INF] AsyncTaskMethodBuilder Fetching servers from moonlight
00:18:25 [INF] ExecutionContext About to receive 0 servers
00:18:25 [INF] ExecutionContext Fetched servers. Closing websocket connection
00:18:25 [INF] AsyncTaskMethodBuilder Finishing boot
00:18:25 [INF] AsyncTaskMethodBuilder Restoring docker containers
00:18:25 [INF] AsyncTaskMethodBuilder Starting ftp server
00:18:25 [INF] AsyncTaskMethodBuilder Ftp server listening on 0.0.0.0:2021
01:27:50 [FTL] ConnectionManager Connection id "0HN50CK5KIT76" application never completed.
01:36:12 [INF] AsyncTaskMethodBuilder`1 Received boot signal from moonlight
01:36:12 [INF] AsyncTaskMethodBuilder Preparing for boot
01:36:13 [INF] AsyncTaskMethodBuilder Fetching servers from moonlight
01:36:13 [INF] ExecutionContext About to receive 4 servers
01:36:13 [INF] ExecutionContext Loaded server 1 [1/4]
01:36:13 [INF] ExecutionContext Loaded server 2 [2/4]
01:36:13 [INF] ExecutionContext Loaded server 5 [3/4]
01:36:13 [INF] ExecutionContext Loaded server 6 [4/4]
01:36:13 [INF] ExecutionContext Fetched servers. Closing websocket connection
01:36:13 [INF] AsyncTaskMethodBuilder Finishing boot
01:36:13 [INF] AsyncTaskMethodBuilder Restoring docker containers
01:36:13 [INF] ExecutionContext Restored server 6 and reattached stream
01:36:13 [INF] ExecutionContext Restored server 2 and reattached stream
01:36:13 [INF] ExecutionContext Restored server 1 and reattached stream
01:42:25 [FTL] ConnectionManager Connection id "0HN50CK5KIT9B" application never completed.
20:13:46 [INF] AsyncTaskMethodBuilder`1 Received boot signal from moonlight
20:13:46 [INF] AsyncTaskMethodBuilder Preparing for boot
20:13:46 [INF] AsyncTaskMethodBuilder Fetching servers from moonlight
20:13:47 [INF] ExecutionContext About to receive 5 servers
20:13:47 [INF] ExecutionContext Loaded server 1 [1/5]
20:13:47 [INF] ExecutionContext Loaded server 2 [2/5]
20:13:47 [INF] ExecutionContext Loaded server 5 [3/5]
20:13:47 [INF] ExecutionContext Loaded server 6 [4/5]
20:13:47 [INF] ExecutionContext Loaded server 7 [5/5]
20:13:47 [INF] ExecutionContext Fetched servers. Closing websocket connection
20:13:47 [INF] AsyncTaskMethodBuilder Finishing boot
20:13:47 [INF] AsyncTaskMethodBuilder Restoring docker containers
20:13:47 [INF] ExecutionContext Restored server 6 and reattached stream
20:13:47 [INF] ExecutionContext Restored server 2 and reattached stream
20:13:47 [INF] ExecutionContext Restored server 1 and reattached stream
20:14:24 [FTL] ConnectionManager Connection id "0HN50CK5KJ77J" application never completed.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Masu-Baumgartner** [comment]
Is already known. Maybe read the checkboxes before you tick them....

" I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system."

**Comment by LowlandwasTaken** [comment]
I have actually searched and i have not found it...
