### ISSUE TITLE
Node Setup Error

### ISSUE THREAD

**Issue by Kartvya69** [Moonlight-Panel/Moonlight#436]
### Current Behavior

The overview page is still not showing even after I followed the docs correctly

### Expected Behavior

The node should work fine

### Steps to Reproduce

Install the Node 

### Panel Version

v2 EA

### Daemon Version

v2 EA

### Error Logs

```bash
08:05:05 [INF] AsyncTaskMethodBuilder Starting MoonlightDaemon v2
08:05:05 [INF] GenericWebHostService Now listening on: http://0.0.0.0:6338
08:05:05 [INF] ConsoleLifetime Application started. Press Ctrl+C to shut down.
08:05:05 [INF] ConsoleLifetime Hosting environment: Production
08:05:05 [INF] ExecutionContext Content root path: /var/lib/moonlight08:05:08 [INF] AsyncTaskMethodBuilder Preparing for boot
08:05:08 [WRN] AsyncTaskMethodBuilder An unknown error occured while
booting
08:05:08 [WRN] AsyncTaskMethodBuilder
System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at MoonCore.Helpers.HttpApiClient`1.SendRaw(HttpMethod method, String path, String body, String contentType, Stream fileStream, String
fileName)
   at MoonCore.Helpers.HttpApiClient`1.Send(HttpMethod method, String path, String body, String contentType, Stream fileStream, String fileName)
   at MoonCore.Helpers.HttpApiClient`1.Post(String path, Object body)   at MoonlightDaemon.App.Services.BootService.Start()
   at MoonlightDaemon.App.Services.BootService.Boot()
08:19:29 [INF] ExecutionContext Application is shutting down...
08:21:17 [INF] AsyncTaskMethodBuilder Starting MoonlightDaemon v2
08:21:18 [INF] GenericWebHostService Now listening on: http://0.0.0.0:9192
08:21:18 [INF] ConsoleLifetime Application started. Press Ctrl+C to shut down.
08:21:18 [INF] ConsoleLifetime Hosting environment: Production
08:21:18 [INF] ExecutionContext Content root path: /var/lib/moonlight08:21:21 [INF] AsyncTaskMethodBuilder Preparing for boot
08:21:21 [INF] AsyncTaskMethodBuilder Fetching servers from moonlight08:21:21 [INF] ExecutionContext About to receive 0 servers
08:21:21 [INF] ExecutionContext Fetched servers. Closing websocket connection
08:21:21 [INF] AsyncTaskMethodBuilder Finishing boot
08:21:21 [INF] AsyncTaskMethodBuilder Restoring docker containers
08:21:21 [INF] AsyncTaskMethodBuilder Starting ftp server
08:21:21 [INF] AsyncTaskMethodBuilder Ftp server listening on 0.0.0.0:9193
08:22:09 [INF] ExecutionContext Application is shutting down...
08:22:09 [INF] AsyncVoidMethodBuilder Stopping ftp server
08:22:10 [INF] AsyncTaskMethodBuilder Starting MoonlightDaemon v2
08:22:10 [INF] GenericWebHostService Now listening on: http://0.0.0.0:9192
08:22:10 [INF] ConsoleLifetime Application started. Press Ctrl+C to shut down.
08:22:10 [INF] ConsoleLifetime Hosting environment: Production
08:22:10 [INF] ExecutionContext Content root path: /var/lib/moonlight08:22:13 [INF] AsyncTaskMethodBuilder Preparing for boot
08:22:13 [INF] AsyncTaskMethodBuilder Fetching servers from moonlight08:22:13 [INF] ExecutionContext About to receive 0 servers
08:22:13 [INF] ExecutionContext Fetched servers. Closing websocket connection
08:22:13 [INF] AsyncTaskMethodBuilder Finishing boot
08:22:13 [INF] AsyncTaskMethodBuilder Restoring docker containers
08:22:13 [INF] AsyncTaskMethodBuilder Starting ftp server
08:22:13 [INF] AsyncTaskMethodBuilder Ftp server listening on 0.0.0.0:9193
08:32:03 [INF] ExecutionContext Application is shutting down...
08:32:03 [INF] AsyncVoidMethodBuilder Stopping ftp server
08:32:04 [INF] AsyncTaskMethodBuilder Starting MoonlightDaemon v2
08:32:04 [INF] GenericWebHostService Now listening on: http://0.0.0.0:9192
08:32:04 [INF] ConsoleLifetime Application started. Press Ctrl+C to shut down.
08:32:04 [INF] ConsoleLifetime Hosting environment: Production
08:32:04 [INF] ExecutionContext Content root path: /var/lib/moonlight08:32:07 [INF] AsyncTaskMethodBuilder Preparing for boot
08:32:07 [INF] AsyncTaskMethodBuilder Fetching servers from moonlight08:32:07 [INF] ExecutionContext About to receive 0 servers
08:32:07 [INF] ExecutionContext Fetched servers. Closing websocket connection
08:32:07 [INF] AsyncTaskMethodBuilder Finishing boot
08:32:07 [INF] AsyncTaskMethodBuilder Restoring docker containers
08:32:07 [INF] AsyncTaskMethodBuilder Starting ftp server
08:32:07 [INF] AsyncTaskMethodBuilder Ftp server listening on 0.0.0.0:9193
08:33:28 [INF] ExecutionContext Application is shutting down...
08:33:28 [INF] AsyncVoidMethodBuilder Stopping ftp server
08:33:28 [INF] AsyncTaskMethodBuilder Starting MoonlightDaemon v2
08:33:28 [INF] GenericWebHostService Now listening on: http://0.0.0.0:9192
08:33:28 [INF] ConsoleLifetime Application started. Press Ctrl+C to shut down.
08:33:28 [INF] ConsoleLifetime Hosting environment: Production
08:33:28 [INF] ExecutionContext Content root path: /var/lib/moonlight08:33:31 [INF] AsyncTaskMethodBuilder Preparing for boot
08:33:32 [INF] AsyncTaskMethodBuilder Fetching servers from moonlight08:33:32 [INF] ExecutionContext About to receive 0 servers
08:33:32 [INF] ExecutionContext Fetched servers. Closing websocket connection
08:33:32 [INF] AsyncTaskMethodBuilder Finishing boot
08:33:32 [INF] AsyncTaskMethodBuilder Restoring docker containers
08:33:32 [INF] AsyncTaskMethodBuilder Starting ftp server
08:33:32 [INF] AsyncTaskMethodBuilder Ftp server listening on 0.0.0.0:9193
08:38:14 [INF] ExecutionContext Application is shutting down...
08:38:14 [INF] AsyncVoidMethodBuilder Stopping ftp server
08:39:55 [INF] AsyncTaskMethodBuilder Starting MoonlightDaemon v2
08:39:56 [INF] GenericWebHostService Now listening on: http://0.0.0.0:8081
08:39:56 [INF] ConsoleLifetime Application started. Press Ctrl+C to shut down.
08:39:56 [INF] ConsoleLifetime Hosting environment: Production
08:39:56 [INF] ExecutionContext Content root path: /var/lib/moonlight08:39:58 [INF] AsyncTaskMethodBuilder Preparing for boot
08:39:59 [INF] AsyncTaskMethodBuilder Fetching servers from moonlight08:39:59 [INF] ExecutionContext About to receive 0 servers
08:39:59 [INF] ExecutionContext Fetched servers. Closing websocket connection
08:39:59 [INF] AsyncTaskMethodBuilder Finishing boot
08:39:59 [INF] AsyncTaskMethodBuilder Restoring docker containers
08:39:59 [INF] AsyncTaskMethodBuilder Starting ftp server
08:39:59 [INF] AsyncTaskMethodBuilder Ftp server listening on 0.0.0.0:2021
08:46:15 [INF] ExecutionContext Application is shutting down...
08:46:15 [INF] AsyncVoidMethodBuilder Stopping ftp server
08:46:54 [INF] AsyncTaskMethodBuilder Starting MoonlightDaemon v2
08:46:55 [INF] GenericWebHostService Now listening on: http://0.0.0.0:8081
08:46:55 [INF] ConsoleLifetime Application started. Press Ctrl+C to shut down.
08:46:55 [INF] ConsoleLifetime Hosting environment: Production
08:46:55 [INF] ExecutionContext Content root path: /var/lib/moonlight08:46:58 [INF] AsyncTaskMethodBuilder Preparing for boot
08:46:58 [INF] AsyncTaskMethodBuilder Fetching servers from moonlight08:46:58 [INF] ExecutionContext About to receive 0 servers
08:46:58 [INF] ExecutionContext Fetched servers. Closing websocket connection
08:46:58 [INF] AsyncTaskMethodBuilder Finishing boot
08:46:58 [INF] AsyncTaskMethodBuilder Restoring docker containers
08:46:58 [INF] AsyncTaskMethodBuilder Starting ftp server
08:46:58 [INF] AsyncTaskMethodBuilder Ftp server listening on 0.0.0.0:2021
08:47:35 [INF] ExecutionContext Application is shutting down...
08:47:35 [INF] AsyncVoidMethodBuilder Stopping ftp server
08:47:36 [INF] AsyncTaskMethodBuilder Starting MoonlightDaemon v2
08:47:36 [INF] GenericWebHostService Now listening on: http://0.0.0.0:8081
08:47:36 [INF] ConsoleLifetime Application started. Press Ctrl+C to shut down.
08:47:36 [INF] ConsoleLifetime Hosting environment: Production
08:47:36 [INF] ExecutionContext Content root path: /var/lib/moonlight08:47:39 [INF] AsyncTaskMethodBuilder Preparing for boot
08:47:39 [INF] AsyncTaskMethodBuilder Fetching servers from moonlight08:47:39 [INF] ExecutionContext About to receive 0 servers
08:47:39 [INF] ExecutionContext Fetched servers. Closing websocket connection
08:47:39 [INF] AsyncTaskMethodBuilder Finishing boot
08:47:39 [INF] AsyncTaskMethodBuilder Restoring docker containers
08:47:39 [INF] AsyncTaskMethodBuilder Starting ftp server
08:47:39 [INF] AsyncTaskMethodBuilder Ftp server listening on 0.0.0.0:2021
08:51:28 [INF] ExecutionContext Application is shutting down...
08:51:28 [INF] AsyncVoidMethodBuilder Stopping ftp server
08:51:28 [INF] AsyncTaskMethodBuilder Starting MoonlightDaemon v2
08:51:29 [INF] GenericWebHostService Now listening on: http://0.0.0.0:8081
08:51:29 [INF] ConsoleLifetime Application started. Press Ctrl+C to shut down.
08:51:29 [INF] ConsoleLifetime Hosting environment: Production
08:51:29 [INF] ExecutionContext Content root path: /var/lib/moonlight08:51:31 [INF] AsyncTaskMethodBuilder Preparing for boot
08:51:32 [INF] AsyncTaskMethodBuilder Fetching servers from moonlight08:51:32 [INF] ExecutionContext About to receive 0 servers
08:51:32 [INF] ExecutionContext Fetched servers. Closing websocket connection
08:51:32 [INF] AsyncTaskMethodBuilder Finishing boot
08:51:32 [INF] AsyncTaskMethodBuilder Restoring docker containers
08:51:32 [INF] AsyncTaskMethodBuilder Starting ftp server
08:51:32 [INF] AsyncTaskMethodBuilder Ftp server listening on 0.0.0.0:2021
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Masu-Baumgartner** [comment]
What overview page? + Attach screenshots

**Comment by Masu-Baumgartner** [comment]
Also you havent included the panel logs

**Comment by Kartvya69** [comment]
Overview page is the node edit page in the moonlightpanel which gives the confirmation of the node working 
![Screenshot_2024-09-05-14-48-08-49](https://github.com/user-attachments/assets/b90bc016-af50-47b0-b1fa-56e274fbcddb)

**Comment by Masu-Baumgartner** [comment]
so the overview page is showing. just the data isnt loading

**Comment by Masu-Baumgartner** [comment]
you need to clarify the issue....

**Comment by Masu-Baumgartner** [comment]
share your node settings

**Comment by Kartvya69** [comment]
Ok, 
![Screenshot_2024-09-05-14-58-50-41](https://github.com/user-attachments/assets/c8083401-3690-4c34-a54f-9e8037d9e7ae)

**Comment by Masu-Baumgartner** [comment]
Your configuration is invalid. The daemon is not reachable. Make sure you dont have any firewall configurations blocking this port and ask for support in our discord server as this is clearly a configuration issue on your side. If you will open a github issue again without checking basic things and claiming its an application bug, you will be blocked from opening issues
